final/Doctor/urls.py
from django.urls import path
from . import views

app_name = 'Doctor'
urlpatterns = [
    path('', views.home_doc, name='home_doc'),
    path('signup/', views.DoctorCreate.as_view(), name='signup_doc'),
    path('login/', views.login_doc, name='login_doc'),
    path('write_a_blog/', views.write_a_blog, name='write_a_blog'),
    path('live_status/', views.live_status, name = 'live_status'),
    path('rating_doc/', views.rating_doc , name='rating_doc'),
]

final/divaDoc/urls.py
from django.urls import path
from . import views

app_name='divaDoc'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),

    #path(''),

    path('blogs/', views.blogs_view, name='blogs'),
#    path('medicines/', views.medicines_view, name='medicines'),

    #### Home
    path('userhome/', views.userhome, name='userhome'),

    #### Appointment
    path('appointment/', views.index_appointment, name='index_appointment'),
    path('appointment/<int:doc_id>', views.detail_appointment, name='detail_appointment'),
    path('appointment/<int:doc_id>/status/', views.status_appointment, name='status_appointment'),
    path('appointment/<int:doc_id>/book/', views.book_appointment, name='book_appointment'),
    path('appointment/<int:doc_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),

    #### Rate
    path('feedback/', views.index_rate, name='feedback'),

    ## discussion forum
    path('discussion_forum/', views.discussion_forum, name='discussion_forum'),

    ## diva_opinion
    path('diva_opinion/', views.diva_opinion, name='diva_opinion'),

    path('user_logout/',views.user_logout, name='user_logout'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('divaDoc.urls')),
    path('medicines/', include('medicines.urls')),
    path('excercise/', include('Excercise.urls')),
    path('doctor/', include('Doctor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/Doctor/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django import forms




"""
#######################################



from collections import OrderedDict

from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX, identify_hasher,
)
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.forms.utils import flatatt
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.html import format_html, format_html_join
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext, ugettext_lazy as _



class ReadOnlyPasswordHashWidget(forms.Widget):
    def render(self, name, value, attrs):
        encoded = value
        final_attrs = self.build_attrs(attrs)

        if not encoded or encoded.startswith(UNUSABLE_PASSWORD_PREFIX):
            summary = mark_safe("<strong>%s</strong>" % ugettext("No password set."))
        else:
            try:
                hasher = identify_hasher(encoded)
            except ValueError:
                summary = mark_safe("<strong>%s</strong>" % ugettext(
                    "Invalid password format or unknown hashing algorithm."))
            else:
                summary = format_html_join('',
                                           "<strong>{}</strong>: {} ",
                                           ((ugettext(key), value)
                                            for key, value in hasher.safe_summary(encoded).items())
                                           )

        return format_html("<div{}>{}</div>", flatatt(final_attrs), summary)


class ReadOnlyPasswordHashField(forms.Field):
    widget = ReadOnlyPasswordHashWidget

"""
######################################
# Create your models here.
class Doctor(models.Model):
    name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    certficate = models.FileField()
    active = models.BooleanField(default = False)
    validity = models.BooleanField(default = False)
    patientName = models.CharField(default='patient',max_length=100)
    time_book1_model = models.CharField(default='time',max_length=10)
    #book_user_id = {}
    #time_book = {}
    rating = models.FloatField(default=0)
    profile = models.CharField(max_length=100, default='')
    
    location = models.CharField(max_length = 200, default='loc')
    available_dates = models.CharField(max_length=200, default='date')
    works_from = models.IntegerField(default=0)
    works_upto = models.IntegerField(default=0)
    curr_status = models.IntegerField(default=0)
    max_status = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('divaDoc:home')

    def __str__(self):
        return self.name

final/Doctor/forms.py
from __future__ import unicode_literals
from collections import OrderedDict
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX, identify_hasher,
)
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.forms.utils import flatatt
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.html import format_html, format_html_join
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext, ugettext_lazy as _



class DocAuthenticationForm(forms.Form):
    username = forms.CharField(max_length=254)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': "Please enter a correct %(username)s and password. "
                           "Note that both fields may be case-sensitive.",
        'inactive': "This account is inactive.",
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(DocAuthenticationForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',

            )

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache





"""
class DocAuthenticationForm(forms.ModelForm):
    username = forms.CharField(max_length = 254)
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': _("Please enter a correct %(username)s and password."
                           "Note that both fields are case-sensitive."),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(DocAuthenticationForm, self).__init__(*args, **kwargs)

        user = get_user_model()
        self.username_field = user._meta.get_field(user.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username, password=password)
            
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code = 'invalid_login',
                    params = {'username': self.username_field.verbose_name},
                )
        else:
            self.confirm_login_allowed(self.user_cache)
        return self.cleaned_data
"""




"""
class DocAuthenticationForm(forms.Form):
    username = forms.CharField(max_length=254)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': "Please enter a correct %(username)s and password. "
                           "Note that both fields may be case-sensitive.",
        'inactive': "This account is inactive.",
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(DocAuthenticationForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data
    
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code = 'inactive',
            )

    def ger_user(self):
        return self.user_cache
        
    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None
"""

final/Doctor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
#from .forms import DocAuthenticationForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Doctor

# Create your views here.
class DoctorCreate(CreateView):
    model = Doctor
    fields = ['name', 'username', 'password', 'certficate', 'profile', 'location', 'available_dates', 'works_from','works_upto', 'curr_status', 'max_status']

def home_doc(request):
    return render(request, 'Doctor/home_doc.html', {})

def signup_doc(request):
    if request.method=='GET':
        q = Testdoc.objects.filter(name__startswith=request.GET['profile'])
        # q = Testdoc.objects.filter(id=1)
        c = q.choice_set.create(name=request.GET['username'], location=request.GET['location'], available_dates=request.GET['available_dates'], works_from=request.GET['works_from'], works_upto=request.GET['works_upto'], curr_status=request.GET['curr_status'], max_booking=request.GET['max_status'])
        c.save()
    return render(request, 'Doctor/doctor_form.html', {})

def login_doc(request):
    if request.method=='POST':
        print (request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        flag = 0
        for doc in Doctor.objects.all():
            if doc.username==username and doc.password==password and doc.validity==True:
                flag = 1
                break
        if flag==1:
            doc.active = True
            return render(request, 'Doctor/home_doc.html', {'doc':doc})
            #return redirect('Doctor:home_doc')
        else:
            return redirect('Doctor:login_doc')
    else:
        form = AuthenticationForm()
    return render(request, 'Doctor/login_doc.html', {'form':form})

def write_a_blog(request):
    return render(request, 'Doctor/write_a_blog.html', {})

def live_status(request):
    return render(request, 'Doctor/live_status.html', {})

def rating_doc(request):
    return render(request, 'Doctor/rating_doc.html', {})

final/Doctor/templates/Doctor/doctor_form.html
{% extends 'divaDoc/base.html' %}
{% block title %}Register{% endblock %}
{% block home_url %}"/"{% endblock %}


{% block home_search %}
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account : Doctor</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
										<form action="" method='post' enctype="multipart/form-data">
											{% csrf_token %}

											{% include 'divaDoc/form_template.html' %}
											<div class="form-group">
													<div class="col-sm-offset-2 col-sm-10">
															<button type="submit" class="btn btn-success">Submit</button>
													</div>
											</div>
										</form>
									</div>
									<div class="panel-footer">
											Already have an account? <a href="{% url 'Doctor:login_doc' %}">Click here</a> to log in.
									</div>
							</div>
					</div>
			</div>

	</div>




{% endblock %}

final/Doctor/templates/Doctor/home_doc.html
{% extends "divaDoc/base.html" %}
{% block home_url %}"{% url 'Doctor:home_doc' %}"{% endblock %}
{% block home_name %}Doc Diva{% endblock %}

{% block home_menu %}
<div class="collapse navbar-collapse navbar-left">
  <ul class="nav navbar-nav navbar-left">
    <li class="{% block status_active %}{% endblock %}"><a href="{% url 'Doctor:live_status' %}"><b>Live Status</b></a></li>
    <li class="{% block blogs_active %}{% endblock %}"><a href="{% url 'Doctor:write_a_blog' %}"><b>Blogs</b></a></li>
  </ul>
</div>
{% endblock %}

{% block nav_right %}
<ul class="nav navbar-nav navbar-right">
  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
</ul>
{%endblock%}
{% block body %}
<h1> Home Doctor </h1>

<div class="albums-container container-fluid">
  <div class="row">

        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id="c1">
            <a href="{% url 'Doctor:write_a_blog' %}">
              <h2 class='x1'>Write a blog</h2>
            </a>
          </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id="c2">
            <a href="{% url 'Doctor:live_status' %}">
              <h2 class='x2'>Live Status</h2>
            </a>
          </div>
        </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
          <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id='c3'>
            <a href="{% url 'Doctor:rating_doc' %}">
              <h2 class='x3'>Your Rating</h2>
            </a>
          </div>
        </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id='c4'>
            <a href="{% url 'divaDoc:feedback' %}">
              <h2 class='x4'>Feedback</h2>
            </a>
          </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}


  </div>
</div>


{% endblock %}

final/Doctor/templates/Doctor/live_status.html
{% extends "Doctor/home_doc.html" %}
{% block status_active %}active{% endblock %}

{% block body %}
<h1><b>Your current status is : </b></h1>

<h3>No appointments yet</h3>
{% endblock %}

final/Doctor/templates/Doctor/login_doc.html
{% extends 'divaDoc/base.html' %}
{% block title %}Log In{% endblock %}
{% block home_url %}"/"{% endblock %}

{% block body %}

<div class="container-fluid">
{% block home_search %}
{% endblock %}
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Doctor Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
										<form action="{% url 'Doctor:login_doc' %}" method='post'>
											{% csrf_token %}
											{% include 'divaDoc/form_template.html' %}

											<div class="form-group">
													<div class="col-sm-offset-2 col-sm-10">
														<button type="submit" class="btn btn-success">Submit</button>
													</div>
											</div>
										</form>
									</div>
	                <div class="panel-footer">
	                    Don't have an account? <a href="{% url 'Doctor:signup_doc' %}">Click here</a> to register.
	                </div>
	            </div>
	        </div>
	    </div>

	</div>

{% endblock %}

final/Doctor/templates/Doctor/rating_doc.html
<h1>Your current rating is </h1>

final/Doctor/templates/Doctor/write_a_blog.html
{% extends "Doctor/home_doc.html" %}
{% block blogs_active %}active{% endblock %}

{%block body%}
<h1><b>Write a blog</b></h1>
<div class="media">
  <div class="media-left media-middle">
    <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" class="media-object" style="width:60px">
  </div>
  <div class="media-body">
    <h4 class="media-heading"><b>Know Before You Go: Allergy Tests</b></h4>
    <p>f you have allergies, you’re not alone. More than 50 million Americans have allergies, making them the sixth most common cause of chronic illness. But it’s not enough to know that you’re one of millions who suffer. To treat allergies more effectively, you first need to know what is causing your allergic reactions. Allergy tests are quick and painless ways to find out. Here’s what you need to know about allergy tests before you head to the appointment.</p>
  </div>
</div>
{% endblock %}