final/Excercise/urls.py
from django.urls import path
from . import views

app_name='Excercise'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:dis_id>/', views.detail, name='detail'),
]

final/divaDoc/urls.py
from django.urls import path
from . import views

app_name='divaDoc'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),

    #path(''),

    path('blogs/', views.blogs_view, name='blogs'),
#    path('medicines/', views.medicines_view, name='medicines'),

    #### Home
    path('userhome/', views.userhome, name='userhome'),

    #### Appointment
    path('appointment/', views.index_appointment, name='index_appointment'),
    path('appointment/<int:doc_id>', views.detail_appointment, name='detail_appointment'),
    path('appointment/<int:doc_id>/status/', views.status_appointment, name='status_appointment'),
    path('appointment/<int:doc_id>/book/', views.book_appointment, name='book_appointment'),
    path('appointment/<int:doc_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),

    #### Rate
    path('feedback/', views.index_rate, name='feedback'),

    ## discussion forum
    path('discussion_forum/', views.discussion_forum, name='discussion_forum'),

    ## diva_opinion
    path('diva_opinion/', views.diva_opinion, name='diva_opinion'),

    path('user_logout/',views.user_logout, name='user_logout'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('divaDoc.urls')),
    path('medicines/', include('medicines.urls')),
    path('excercise/', include('Excercise.urls')),
    path('doctor/', include('Doctor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/Excercise/models.py
from django.db import models

# Create your models here.

class disease(models.Model):
    dis_name = models.CharField(max_length = 50)
    def __str__(self):
        return self.dis_name

class excercise(models.Model):
    dis = models.ForeignKey(disease, on_delete=models.CASCADE, related_name='choice_set')
    ex_name = models.CharField(max_length = 50)
    anim = models.FileField(null=True, blank=True)
    def __str__(self):
        return self.ex_name

final/Excercise/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import disease, excercise
from django.urls import reverse

# Create your views here.

def index(request):
    dis = disease.objects.order_by('id')
    return render(request, 'Excercise/index.html', {'dis': dis})

def detail(request, dis_id):
    dise = get_object_or_404(disease, pk=dis_id)
    return render(request, 'Excercise/detail.html', {'dise': dise})

final/Excercise/templates/Excercise/detail.html
<style>
	#a1{
		padding: 10px 20px;
		background-color: black;
		color: white;
		cursor: pointer;
	}
	#a1:hover{
		background-color: rgb(120,120,120);
	}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
/*$(document).ready(function(){
  $(".x1").mouseenter(function(){
    $(".n2").slideToggle(2000);
  });
  $(".x1").mouseleave(function(){
    $(".n2").css("background-color", "lightgray");
  });
});*/
</script>

{% extends "divaDoc/base.html" %}

{% block home_url %}
{% if user.is_active %}
	"{% url 'divaDoc:userhome' %}"
{% else%}
	"/"
{%endif%}
{% endblock %}

{% block home_name %}
{% if user.is_active %}
	{{user.username}}
{% else%}
	Diva Doc
{%endif%}
{% endblock %}

{% block home_search %}

<!--<div class="collapse navbar-collapse" id="topNavBar">-->
<form class="navbar-form navbar-left" role="search" method="get" action="#">
  <div class="form-group">
    <input type="text" class="form-control" name="q" value="">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>
<!--</div>-->
{% endblock %}
{% block title %}Buy Medicines{% endblock %}
{% block medicine_active %}active{% endblock %}
{% block nav_right %}
  {% if user.is_active %}
	<ul class="nav navbar-nav navbar-right">
	  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
	</ul>
  {% else %}
	<ul class="nav navbar-nav navbar-left">
		<li class="{% block register_active %}{% endblock %}"><a href="{% url 'divaDoc:signup' %}" >Register</a></li>
		<li class="{% block login_active %}{% endblock %}"><a href="{% url 'divaDoc:login' %}" >Log In</a></li>
	</ul>
{% endif %}
{%endblock%}

{% block body %}

<div class="container-fluid">
	<div>
		{% if dise.choice_set.all %}
			{% for d in dise.choice_set.all %}
				
				<script>
					$(document).ready(function(){
						$(".x{{d.id}}").click(function(){
							$(".n{{d.id}}").slideToggle(500);
						});
						$(".x{{d.id}}").on({
							mouseenter: function(){
								$(".m{{d.id}}").animate({fontSize: '40px'}, 300);
							},
							mouseleave: function(){
								$(".m{{d.id}}").animate({fontSize: '25px'}, 300);
							}
						});
					});
					

				</script>

				<div>
					<div class="x{{d.id}}" id="a1">
							<h2 style="display: block;" class="m{{d.id}}">{{ d.ex_name }}</h2>
							<div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Animation : </b> 
                                <img src="{{ d.anim.url }}">
                            </div>
							<!--div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Drug Class : </b> {{ d.drug_class }}</div>
							<div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Others : </b> <p>{{ d.other }}</p></div-->
					</div>
				</div>
				{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
			{% endfor %}
		{% else %}
			<h2> Sorry, no Excercise added !!</h2>
		{% endif %}
	</div>
</div>

{% endblock%}

































<!--style>
	.y1{
		color: green;
		font-size: 40px;
		text-decoration: None;
	}
	
	.y2{
		font-size: 40px;
		color: red;
	}
</style>
{% if dise.choice_set.all %}
	{% for d in dise.choice_set.all %}
		<p class="y1">{{ d.ex_name }}</p>
	{% endfor %}
{% else %}
	<p class="y2"> Sorry, no excercise added :( </p>
{% endif %}
-->

final/Excercise/templates/Excercise/index.html
{% extends "divaDoc/base.html" %}



{% block body %}
<style>
	.n1{
		color: red;
		font-size: 40px;
	}

	.y1{
		font-size: 30px;
		text-decoration: None;
		padding: 20px;
		margin: 10px;
	}
	.y1:hover{
		color: white;
	}

	.y2{
		padding: 20px;
		background-color: rgb(180,180,180);
		margin: 20px;
		border-radius: : 2px;
	}
</style>
{% if dis %}
	{% for d in dis %}
		<p class="y2"><a href="{% url 'Excercise:detail' d.id %}" class="y1"> <b> {{ d.dis_name }} </b> </a></p>
	{% endfor %}
{% else %}
	<span class="n1"> Sorry, no Disease added !!</span>
{% endif %}
{% endblock %}