final/Doctor/urls.py
from django.urls import path
from . import views

app_name = 'Doctor'
urlpatterns = [
    path('', views.home_doc, name='home_doc'),
    path('signup/', views.DoctorCreate.as_view(), name='signup_doc'),
    path('login/', views.login_doc, name='login_doc'),
    path('write_a_blog/', views.write_a_blog, name='write_a_blog'),
    path('live_status/', views.live_status, name = 'live_status'),
    path('rating_doc/', views.rating_doc , name='rating_doc'),
]

final/Excercise/urls.py
from django.urls import path
from . import views

app_name='Excercise'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:dis_id>/', views.detail, name='detail'),
]

final/divaDoc/urls.py
from django.urls import path
from . import views

app_name='divaDoc'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),

    #path(''),

    path('blogs/', views.blogs_view, name='blogs'),
#    path('medicines/', views.medicines_view, name='medicines'),

    #### Home
    path('userhome/', views.userhome, name='userhome'),

    #### Appointment
    path('appointment/', views.index_appointment, name='index_appointment'),
    path('appointment/<int:doc_id>', views.detail_appointment, name='detail_appointment'),
    path('appointment/<int:doc_id>/status/', views.status_appointment, name='status_appointment'),
    path('appointment/<int:doc_id>/book/', views.book_appointment, name='book_appointment'),
    path('appointment/<int:doc_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),

    #### Rate
    path('feedback/', views.index_rate, name='feedback'),

    ## discussion forum
    path('discussion_forum/', views.discussion_forum, name='discussion_forum'),

    ## diva_opinion
    path('diva_opinion/', views.diva_opinion, name='diva_opinion'),

    path('user_logout/',views.user_logout, name='user_logout'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('divaDoc.urls')),
    path('medicines/', include('medicines.urls')),
    path('excercise/', include('Excercise.urls')),
    path('doctor/', include('Doctor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/medicines/urls.py
from django.urls import path
from . import views

app_name='medicines'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:dis_id>/', views.detail, name='detail'),
]

final/divaDoc/models.py
from django.db import models

# Create your models here.

class Testdoc(models.Model):
    d_type = models.CharField(max_length = 25)
    def __str__(self):
        return self.d_type

class TestChoice(models.Model):
    doc = models.ForeignKey(Testdoc, on_delete=models.CASCADE, related_name='choice_set')
    name = models.CharField(max_length = 50)
    location = models.CharField(max_length = 50)
    available_dates = models.CharField(max_length = 200)
    works_from = models.IntegerField()
    works_upto = models.IntegerField()
    init_date = models.IntegerField(default = 1)
    curr_status = models.IntegerField(default = 0)
    max_booking = models.IntegerField(default = 70)
    def __str__(self):
        return self.name


    
##################### RATING
    
class rateapp(models.Model):
    rating = models.IntegerField(default=0)


"""
class disease(models.Model):
    dis_name = models.CharField(max_length = 50)
    def __str__(self):
        return self.dis_name

class medicine(models.Model):
    dis = models.ForeignKey(disease, on_delete=models.CASCADE, related_name='choice_set')
    med_name = models.CharField(max_length = 50)
    def __str__(self):
        return self.med_name
"""

final/divaDoc/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

final/divaDoc/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Testdoc, TestChoice, rateapp
from django.urls import reverse

global k

def home(request):
    return render(request, 'divaDoc/home.html', {})

def signup_view(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('divaDoc:userhome')
    else:
        form = UserCreationForm()
    return render(request, 'divaDoc/signup.html', {'form': form})

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            global k
            k = user
            login(request, user)
            return redirect('divaDoc:userhome')

    else:
        form = AuthenticationForm()
    return render(request, 'divaDoc/login.html', {'form': form})


"""
###### MEDICINES ####################################
def index_med(request):
    dis = disease.objects.order_by('id')
    return render(request, 'divaDoc/index_med.html', {'dis': dis})

def detail_med(request, dis_id):
    dise = get_object_or_404(disease, pk=dis_id)
    return render(request, 'divaDoc/detail_med.html', {'dise': dise})
"""

"""
def medicines_view(request):
    return render(request, 'divaDoc/medicines.html')
"""

def blogs_view(request):
    return render(request, 'divaDoc/blogs.html')


####logout
def user_logout(request):
    logout(request)
    form = AuthenticationForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'divaDoc/login.html', context)



############################  HOME  ##################

def userhome(request):
    return render(request, 'divaDoc/index_home.html',{'k':k})





##### Appointment ##################################

def index_appointment(request):
    doc = Testdoc.objects.order_by('id')
    return render(request, 'divaDoc/index_appointment.html', {'doc': doc})

def detail_appointment(request, doc_id):
    doctor = get_object_or_404(Testdoc, pk=doc_id)
    return render(request, 'divaDoc/detail_appointment.html', {'doctor': doctor})

def status_appointment(request, doc_id):
    doctor = get_object_or_404(Testdoc, pk=doc_id)
    return render(request, 'divaDoc/status_appointment.html', {'doctor': doctor})

def book_appointment(request, doc_id):
    doctor = get_object_or_404(Testdoc, pk=doc_id)
    try:
        selected_choice = doctor.choice_set.get(pk=request.POST['choice'])
    except(KeyError, TestChoice.DoesNotExist):
        context = {
            'doctor': doctor,
            'error_message': "You didn't select any doctor.",
        }
        return render(request, 'divaDoc/detail_appointment.html', context)
    else:
        if(selected_choice.curr_status < selected_choice.max_booking):
            selected_choice.curr_status += 1
            selected_choice.save()
        else:
            return HttpResponse('Sorry , appointment full for today !!')
        return HttpResponseRedirect(reverse('divaDoc:status_appointment', args=(doctor.id,)))

def cancel_appointment(request, doc_id):
    doctor = get_object_or_404(Testdoc, pk=doc_id)
    try:
        selected_choice = doctor.choice_set.get(pk=request.POST['choice'])
    except(KeyError, TestChoice.DoesNotExist):
        context = {
            'doctor': doctor,
            'error_message': "You didn't select any doctor.",
        }
        return render(request, 'divaDoc/detail_appointment.html', context)
    else:
        if(selected_choice.curr_status > 0):
            selected_choice.curr_status -= 1
            selected_choice.save()
        else:
            return HttpResponse("You didn't book this doctor !")
        return HttpResponseRedirect(reverse('divaDoc:status_appointment', args=(doctor.id,)))



############# RATE ##############

def index_rate(request):
    rat = rateapp.objects.order_by('id')
    return render(request, 'divaDoc/index_rate.html', {})


############  Diva Opinion ##########

def diva_opinion(request):
    return render(request, 'divaDoc/diva_opinion.html', {})

def discussion_forum(request):
    return render(request, 'divaDoc/discussion_forum.html', {})

"""
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                #return redirect('')
                return render(request, 'divaDoc/home.html', {})
            else:
                return render(request, 'divaDoc/login_form.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'divaDoc/login_form.html', {'error_message': 'Invalid login'})
    return render(request, 'divaDoc/login_form.html')


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return redirect('/')
                #return render(request, 'divaDoc/home.html', {})
    context = {
        "form": form,
    }
    return render(request, 'divaDoc/signup_form.html', context)
"""

final/divaDoc/templates/divaDoc/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTH-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Doc Diva{% endblock %}</title>
  {%load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href = "https://fonts.googleapis.com/css?family=Satisfy">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'divaDoc/style.css'%}">
</head>
<body>
<div>

  <nav class="navbar navbar-inverse ">
    <div class="container-fluid">



      <div class="navbar-header">
        <a class="navbar-brand" href={% block home_url %}{% endblock %}>{% block home_name %}Diva Doc{% endblock %}</a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>

      {% block home_menu %}
      <div class="collapse navbar-collapse navbar-left">
        <ul class="nav navbar-nav navbar-left">
          <li ><a href="{% url 'medicines:index' %}"><b>Medicines</b></a></li>
          <li ><a href="{% url 'divaDoc:blogs' %}"><b>Blogs</b></a></li>
        </ul>
      </div>
      {% endblock %}

      <div class="collapse navbar-collapse navbar-right" id="topNavBar">
        {% block home_search %}
        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
        {% endblock %}
        {% block nav_right %}
        <ul class="nav navbar-nav navbar-left">
          <li class="dropdown {% block register_active %}{% endblock %}"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Sign Up<span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="presentation"><a href="{% url 'divaDoc:signup' %}">As Patient</a></li>
                                        <li role="presentation"><a href="{% url 'Doctor:signup_doc' %}">As Doctor</a></li>
                                    </ul>
                                </li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Log In <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li role="presentation"><a href="{% url 'divaDoc:login' %}">As Patient</a></li>
                                        <li role="presentation"><a href="{% url 'Doctor:login_doc' %}">As Doctor</a></li>
                                    </ul>
                                </li>
        </ul>

        {%endblock%}





      </div>

    </div>
  </nav>
</div>
{% block body %}
{% endblock%}


</body>
</html>

final/divaDoc/templates/divaDoc/blogs.html
{% extends "divaDoc/base.html" %}
{% block home_url %}
{% if user.is_active %}
	"{% url 'divaDoc:userhome' %}"
{% else%}
	"/"
{%endif%}
{% endblock %}

{% block home_name %}
{% if user.is_active %}
	{{user.username}}
{% else%}
	Diva Doc
{%endif%}
{% endblock %}



{% block title %}Blogs{% endblock %}
{% block blogs_active %}active{% endblock %}


{% block nav_right %}

  {% if user.is_active %}
	<ul class="nav navbar-nav navbar-right">
	  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
	</ul>
  {% else %}
	<ul class="nav navbar-nav navbar-left">
		<li class="dropdown {% block register_active %}{% endblock %}"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Sign Up<span class="caret"></span></a>
															<ul class="dropdown-menu" role="menu">
																	<li role="presentation"><a href="{% url 'divaDoc:signup' %}">As Patient</a></li>
																	<li role="presentation"><a href="{% url 'Doctor:signup_doc' %}">As Doctor</a></li>
															</ul>
													</li>
    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Log In <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                  <li role="presentation"><a href="{% url 'divaDoc:login' %}">As Patient</a></li>
                                  <li role="presentation"><a href="{% url 'Doctor:login_doc' %}">As Doctor</a></li>
                              </ul>
                          </li>
	</ul>
{% endif %}
{%endblock%}
{% block body %}


<b>
<pre><h1>		  	Health Blogs</h1></pre></b>


<div class="media">
  <div class="media-left media-middle">
    <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" class="media-object" style="width:60px">
  </div>
  <div class="media-body">
    <h4 class="media-heading"><b>Know Before You Go: Allergy Tests</b></h4>
    <p>f you have allergies, you’re not alone. More than 50 million Americans have allergies, making them the sixth most common cause of chronic illness. But it’s not enough to know that you’re one of millions who suffer. To treat allergies more effectively, you first need to know what is causing your allergic reactions. Allergy tests are quick and painless ways to find out. Here’s what you need to know about allergy tests before you head to the appointment.</p>
  </div>
</div>

<div class="media">
  <div class="media-right media-middle">
    <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" class="media-object" style="width:60px">
  </div>
  <div class="media-body">
    <h4 class="media-heading"><b>The Full Helping </b></h4>
    <p>Gena Hamshaw’s blog is bursting with fresh recipes (all vegan!) and lifestyle tips that will keep you coming back for seconds. The Full Helping celebrates healthy living with a personal touch, which is both refreshing and encouraging to those who may have struggled with eating disorders or who are still on the fence about taking the plunge into better food choices.</p>
  </div>
</div>

{% endblock%}

final/divaDoc/templates/divaDoc/detail_appointment.html
<style>
	.hh1{
		color: Black;
		font-family: "Algerian";
		font-size: 50px;
		text-align: center;
	}
	
	.t0{
		padding: 2px 58px;
		margin: 1px;
	}

	.t1{
		width: 100%;
		color: white;
		font-size: 26px;
		padding: 4px 70px;
		margin: 1px;
		background-color: rgb(200,200,120);
	}
	
	.t1:hover{
		color: white;
		background-color: black;
	}
	
	.t2{
		width: 100%;
		font-size: 20px;
		padding: 4px 70px;
		margin: 1px;
		background-color: rgb(120,200,120);
	}
	
	.t2:hover{
		color: white;
		background-color: green;
	}
	
	.i1{
		padding: 10px 20px;
		background-color: rgb(120,250,120);
		border-radius: 4px;
		cursor: pointer;
		font-size: 30px;
	}
	
	.i1:hover{
		background-color: rgb(0,50,0);
		color: white;
	}
	
	.i2{
		padding: 10px 20px;
		background-color: red;
		border-radius: 4px;
		cursor: pointer;
		font-size: 30px;
	}
	
	.i2:hover{
		background-color: rgb(200,20,20);
		color: white;
	}
	
	input[type='radio']{
		transform: scale(1.5);
	}
</style>

<h1 class="hh1"> {{ doctor.d_type }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'divaDoc:book_appointment' doctor.id %}" method="post">
{% csrf_token %}
<table>
	<tr class="t1"> 
		<th class="t0">	Book </th>
		<th class="t0"> Name </th> 
		<th class="t0"> Location </th>
		<th class="t0"> Available Dates </th>
		<th class="t0"> Working hour</th>
		<th class="t0"> Status </th>
	</tr>
{% for choice in doctor.choice_set.all %}
	<tr class='t2'> 
		<th>	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">	</th>
		<th>	<label for="choice{{ forloop.counter }}">{{ choice.name }}</label>	</th>
		<th>	{{ choice.location }}	</th>
		<th>	{{ choice.available_dates }}	</th>
		<th class="t0"> {{ choice.works_from }} - {{ choice.works_upto }} </th>
		<th class="t0"> {{ choice.curr_status }}/{{ choice.max_booking }} </th>
	</tr>
{% endfor %}
</table>
<input type="submit" value="Confirm Booking" class="i1">
</form>


<form action="{% url 'divaDoc:cancel_appointment' doctor.id %}" method="post">
{% csrf_token %}
<table>
	<tr class="t1"> 
		<th class="t0">	Book </th>
		<th class="t0"> Name </th> 
		<th class="t0"> Location </th>
		<th class="t0"> Available Dates </th>
		<th class="t0"> Working hour</th>
		<th class="t0"> Status </th>
	</tr>
{% for choice in doctor.choice_set.all %}
	<tr class='t2'> 
		<th>	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">	</th>
		<th>	<label for="choice{{ forloop.counter }}">{{ choice.name }}</label>	</th>
		<th>	{{ choice.location }}	</th>
		<th>	{{ choice.available_dates }}	</th>
		<th class="t0"> {{ choice.works_from }} - {{ choice.works_upto }} </th>
		<th class="t0"> {{ choice.curr_status }}/{{ choice.max_booking }} </th>
	</tr>
{% endfor %}
</table>
<input type="submit" value="Cancel Booking" class="i2">
</form>

final/divaDoc/templates/divaDoc/discussion_forum.html
<h1>Discussion Forum</h1>

final/divaDoc/templates/divaDoc/home.html
<style>
  h2{
    text-decoration: None;
  }
  h2:hover{
    font-size: 30px;
  }

</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
/*$(document).ready(function(){
  $("#c1").click(function(){
    $('.x1').animate({
      fontSize: '40px';
    },'slow');
  });
});*/
</script>



{% extends "divaDoc/base.html" %}
{% block home_url %}"/"{% endblock %}
{% block home_name %}Diva Doc{% endblock %}




{% block body %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://images.wallpaperscraft.com/image/mom_close_up_child_baby_children_hand_17864_1280x720.jpg" alt="Los Angeles" height="450" width="1900">
    </div>

    <div class="item">
      <img src="https://www.vactualpapers.com/wallpapers/a-woman-wearing-pink-shoes-running-on-the-road-with-autumn-leaves-health-hd-wallpaper/download/2880x1800.jpg" alt="Chicago" height="450" width="1900">
    </div>

    <div class="item">
      <img src="https://ak8.picdn.net/shutterstock/videos/14718808/thumb/1.jpg" alt="New York" height="450" width="1900">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<pre>
  <h1>                                    <b>Welcome to doc Diva</b></h1>


  <div class="albums-container container-fluid">
  	<div class="row">

  				<div class="col-sm-4 col-lg-2">
  					<div class="thumbnail" id="c1">
  						<a href="{% url 'divaDoc:login' %}">
  							<h2 class='x1'>Appointments</h2>
  						</a>
  					</div>
          </div>
          {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
          <div class="col-sm-4 col-lg-2">
            <div class="thumbnail" id="c2">
  						<a href="{% url 'divaDoc:blogs' %}">
  							<h2 class='x2'>Blogs</h2>
  						</a>
  					</div>
          </div>
            	{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            <div class="col-sm-4 col-lg-2">
            <div class="thumbnail" id='c3'>
  						<a href="{% url 'divaDoc:login' %}">
  							<h2 class='x3'>Exercises</h2>
  						</a>
  					</div>
          </div>
            	{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
          <div class="col-sm-4 col-lg-2">
            <div class="thumbnail" id='c4'>
  						<a href="{% url 'divaDoc:login' %}">
  							<h2 class='x4'>Medicines</h2>
  						</a>
  					</div>
          </div>
  				{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}


  	</div>
  </div>
</pre>
{% endblock %}

final/divaDoc/templates/divaDoc/index_home.html
{% extends "divaDoc/base.html" %}
{% block home_url %}"{% url 'divaDoc:userhome' %}"{% endblock %}
{% block home_name %}{{user.username}}{% endblock %}

{% block nav_right %}
<ul class="nav navbar-nav navbar-right">
  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
</ul>
{%endblock%}
{% block body %}
<pre><h1><b>                                   Welcome {{user.username}}</b></h1></pre>

<div class="albums-container container-fluid">
  <div class="row">

        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id="c1">
            <a href="{% url 'divaDoc:index_appointment' %}">
              <h2 class='x1'>Appointments</h2>
            </a>
          </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id="c2">
            <a href="{% url 'divaDoc:blogs' %}">
              <h2 class='x2'>Blogs</h2>
            </a>
          </div>
        </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
          <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id='c3'>
            <a href="{% url 'Excercise:index' %}">
              <h2 class='x3'>Exercises</h2>
            </a>
          </div>
        </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id='c4'>
            <a href="{% url 'medicines:index' %}">
              <h2 class='x4'>Medicines</h2>
            </a>
          </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail" id='c4'>
            <a href="{% url 'divaDoc:feedback' %}">
              <h2 class='x4'>Feedback</h2>
            </a>
          </div>
        </div>

  </div>
</div>


{% endblock %}

final/divaDoc/templates/divaDoc/login.html
{% extends 'divaDoc/base.html' %}
{% block title %}Log In{% endblock %}
{% block home_url %}"/"{% endblock %}


{% block home_search %}
{% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Patient Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
										<form action="{% url 'divaDoc:login' %}" method='post'>
											{% csrf_token %}
											{% include 'divaDoc/form_template.html' %}

											<div class="form-group">
													<div class="col-sm-offset-2 col-sm-10">
															<button type="submit" class="btn btn-success">Submit</button>
													</div>
											</div>
										</form>
									</div>
	                <div class="panel-footer">
	                    Don't have an account? <a href="{% url 'divaDoc:signup' %}">Click here</a> to register.
	                </div>
	            </div>
	        </div>
	    </div>

	</div>

{% endblock %}

final/divaDoc/templates/divaDoc/signup.html
{% extends 'divaDoc/base.html' %}
{% block title %}Register{% endblock %}
{% block home_url %}"/"{% endblock %}


{% block home_search %}
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account : Patient</h3>
										{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
										<form action="{% url 'divaDoc:signup' %}" method='post'>
											{% csrf_token %}
											<!--{{ form }}    <input type='submit' value="Register">-->
											{% include 'divaDoc/form_template.html' %}
											<div class="form-group">
													<div class="col-sm-offset-2 col-sm-10">
															<button type="submit" class="btn btn-success">Submit</button>
													</div>
											</div>
										</form>
									</div>
									<div class="panel-footer">
											Already have an account? <a href="{% url 'divaDoc:login' %}">Click here</a> to log in.
									</div>
							</div>
					</div>
			</div>

	</div>




{% endblock %}

final/divaDoc/templates/divaDoc/status_appointment.html
<h1> {{ doctor.d_type }} </h1>
{% for choice in doctor.choice_set.all %}
	<span> {{ choice.name }} -- {{ choice.curr_status }} booked </span>
	<br>
{% endfor %}
<a href="{% url 'divaDoc:detail_appointment' doctor.id %}">Book Again ? </a>