final/Doctor/urls.py
from django.urls import path
from . import views

app_name = 'Doctor'
urlpatterns = [
    path('', views.home_doc, name='home_doc'),
    path('signup/', views.DoctorCreate.as_view(), name='signup_doc'),
    path('login/', views.login_doc, name='login_doc'),
    path('write_a_blog/', views.write_a_blog, name='write_a_blog'),
    path('live_status/', views.live_status, name = 'live_status'),
    path('rating_doc/', views.rating_doc , name='rating_doc'),
]

final/divaDoc/urls.py
from django.urls import path
from . import views

app_name='divaDoc'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),

    #path(''),

    path('blogs/', views.blogs_view, name='blogs'),
#    path('medicines/', views.medicines_view, name='medicines'),

    #### Home
    path('userhome/', views.userhome, name='userhome'),

    #### Appointment
    path('appointment/', views.index_appointment, name='index_appointment'),
    path('appointment/<int:doc_id>', views.detail_appointment, name='detail_appointment'),
    path('appointment/<int:doc_id>/status/', views.status_appointment, name='status_appointment'),
    path('appointment/<int:doc_id>/book/', views.book_appointment, name='book_appointment'),
    path('appointment/<int:doc_id>/cancel/', views.cancel_appointment, name='cancel_appointment'),

    #### Rate
    path('feedback/', views.index_rate, name='feedback'),

    ## discussion forum
    path('discussion_forum/', views.discussion_forum, name='discussion_forum'),

    ## diva_opinion
    path('diva_opinion/', views.diva_opinion, name='diva_opinion'),

    path('user_logout/',views.user_logout, name='user_logout'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('divaDoc.urls')),
    path('medicines/', include('medicines.urls')),
    path('excercise/', include('Excercise.urls')),
    path('doctor/', include('Doctor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/medicines/urls.py
from django.urls import path
from . import views

app_name='medicines'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:dis_id>/', views.detail, name='detail'),
]

final/medicines/models.py
from django.db import models

# Create your models here.

class disease(models.Model):
    dis_name = models.CharField(max_length = 50)
    def __str__(self):
        return self.dis_name

class medicine(models.Model):
    dis = models.ForeignKey(disease, on_delete=models.CASCADE, related_name='choice_set')
    med_name = models.CharField(max_length = 50)
    generic_name = models.CharField(max_length = 100, default='')
    drug_class = models.CharField(max_length = 100, default='')
    other = models.CharField(max_length = 5000, default='')
    def __str__(self):
        return self.med_name

final/medicines/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import disease, medicine
from django.urls import reverse

# Create your views here.

def index(request):
    dis = disease.objects.order_by('id')
    return render(request, 'medicines/index.html', {'dis': dis})

def detail(request, dis_id):
    dise = get_object_or_404(disease, pk=dis_id)
    return render(request, 'medicines/detail.html', {'dise': dise})

final/medicines/templates/medicines/detail.html
<style>
	#a1{
		padding: 10px 20px;
		background-color: black;
		color: white;
		cursor: pointer;
	}
	#a1:hover{
		background-color: rgb(120,120,120);
	}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
/*$(document).ready(function(){
  $(".x1").mouseenter(function(){
    $(".n2").slideToggle(2000);
  });
  $(".x1").mouseleave(function(){
    $(".n2").css("background-color", "lightgray");
  });
});*/
</script>

{% extends "divaDoc/base.html" %}

{% block home_url %}
{% if user.is_active %}
	"{% url 'divaDoc:userhome' %}"
{% else%}
	"/"
{%endif%}
{% endblock %}

{% block home_name %}
{% if user.is_active %}
	{{user.username}}
{% else%}
	Diva Doc
{%endif%}
{% endblock %}

{% block home_search %}

<!--<div class="collapse navbar-collapse" id="topNavBar">-->
<form class="navbar-form navbar-left" role="search" method="get" action="#">
  <div class="form-group">
    <input type="text" class="form-control" name="q" value="">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>
<!--</div>-->
{% endblock %}
{% block title %}Buy Medicines{% endblock %}
{% block medicine_active %}active{% endblock %}
{% block nav_right %}
  {% if user.is_active %}
	<ul class="nav navbar-nav navbar-right">
	  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
	</ul>
  {% else %}
	<ul class="nav navbar-nav navbar-left">
		<li class="dropdown {% block register_active %}{% endblock %}"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Sign Up<span class="caret"></span></a>
															<ul class="dropdown-menu" role="menu">
																	<li role="presentation"><a href="{% url 'divaDoc:signup' %}">As Patient</a></li>
																	<li role="presentation"><a href="{% url 'Doctor:signup_doc' %}">As Doctor</a></li>
															</ul>
													</li>
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Log In <span class="caret"></span></a>
	                            <ul class="dropdown-menu" role="menu">
	                                <li role="presentation"><a href="{% url 'divaDoc:login' %}">As Patient</a></li>
	                                <li role="presentation"><a href="{% url 'Doctor:login_doc' %}">As Doctor</a></li>
	                            </ul>
	                        </li>
	</ul>
{% endif %}
{%endblock%}

{% block body %}

<div class="container-fluid">
	<div>
		{% if dise.choice_set.all %}
			{% for d in dise.choice_set.all %}

				<script>
					$(document).ready(function(){
						$(".x{{d.id}}").click(function(){
							$(".n{{d.id}}").slideToggle(500);
						});
						$(".x{{d.id}}").on({
							mouseenter: function(){
								$(".m{{d.id}}").animate({fontSize: '40px'}, 300);
							},
							mouseleave: function(){
								$(".m{{d.id}}").animate({fontSize: '25px'}, 300);
							}
						});
					});


				</script>

				<div>
					<div class="x{{d.id}}" id="a1">
							<h2 style="display: block;" class="m{{d.id}}">{{ d.med_name }}</h2>
							<div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Generic Name : </b> {{ d.generic_name }}</div>
							<div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Drug Class : </b> {{ d.drug_class }}</div>
							<div class="n{{d.id}}" style="display: None"><b style="font-size: 15px;">Others : </b> <p>{{ d.other }}</p></div>
					</div>
				</div>
				{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
			{% endfor %}
		{% else %}
			<h2> Sorry, no Medicine added !!</h2>
		{% endif %}
	</div>
</div>

{% endblock%}

final/medicines/templates/medicines/index.html
{% extends "divaDoc/base.html" %}

{% block home_url %}
{% if user.is_active %}
	"{% url 'divaDoc:userhome' %}"
{% else%}
	"/"
{%endif%}
{% endblock %}

{% block home_name %}
{% if user.is_active %}
	{{user.username}}
{% else%}
	Diva Doc
{%endif%}
{% endblock %}

{% block home_search %}
<!--<div class="collapse navbar-collapse" id="topNavBar">-->
<form class="navbar-form navbar-left" role="search" method="get" action="#">
  <div class="form-group">
    <input type="text" class="form-control" name="q" value="">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>
<!--</div>-->
{% endblock %}
{% block title %}Buy Medicines{% endblock %}
{% block medicine_active %}active{% endblock %}
{% block nav_right %}
  {% if user.is_active %}
	<ul class="nav navbar-nav navbar-right">
	  <li class="active"><a href="{% url 'divaDoc:user_logout' %}">Log Out</a></li>
	</ul>
  {% else %}
	<ul class="nav navbar-nav navbar-left">
		<li class="dropdown {% block register_active %}{% endblock %}"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Sign Up<span class="caret"></span></a>
															<ul class="dropdown-menu" role="menu">
																	<li role="presentation"><a href="{% url 'divaDoc:signup' %}">As Patient</a></li>
																	<li role="presentation"><a href="{% url 'Doctor:signup_doc' %}">As Doctor</a></li>
															</ul>
													</li>
	 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Log In <span class="caret"></span></a>
	                            <ul class="dropdown-menu" role="menu">
	                                <li role="presentation"><a href="{% url 'divaDoc:login' %}">As Patient</a></li>
	                                <li role="presentation"><a href="{% url 'Doctor:login_doc' %}">As Doctor</a></li>
	                            </ul>
	                        </li>
	</ul>
{% endif %}
{%endblock%}

{% block body %}

<div class="albums-container container-fluid">
	<div class="row">
		{% if dis %}
			{% for d in dis %}
				<div class="col-sm-4 col-lg-2">
					<div class="thumbnail">
						<a href="{% url 'medicines:detail' d.id %}">
							<h2>{{ d.dis_name }}</h2>
						</a>

					</div>
				</div>
				{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
			{% endfor %}
		{% else %}
			<span class="n1"> Sorry, no Disease added !!</span>
		{% endif %}
	</div>
</div>

{% endblock%}